name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: git clone
      run: git clone https://github.com/Mahesh096/dagster-ec2deploy.git
    - name: Clone Git Repository
      run: |
          cd dagster-ec2deploy
          sudo docker-compose up
          

