name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: git clone
      run: git clone https://github.com/Mahesh096/dagster-ec2deploy.git
           cd dagster-ec2deploy
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker-compose
      run: docker-compose up

