name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: git clone
      run: |
          cd dagster-ec2deploy
          docker-compose up

