name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Clone Git Repository
      run: |
          git clone https://github.com/Mahesh096/dagster-ec2deploy.git
          cd dagster-ec2deploy
          sudo docker-compose up
          

