name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: delete gitrepo
      run: rm -r dagster-ec2deploy/

    - name: git clone
      run: |
        git clone https://github.com/Mahesh096/dagster-ec2deploy.git
        
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
      
    - name: Clone Git Repository
      run: |
          cd dagster-ec2deploy
          sudo docker-compose up
      

