name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y git

      - name: Clone Git Repository
        run: |
          git clone https://github.com/Mahesh096/dagster-ec2deploy.git
          cd dagster-ec2deploy
          docker-compose up
